a=input("First Name: ")
b=input("Last Name: ")
c=input("Cont. no.: ")
d=input("D.O.B: ")
e=input("College: ")
f=input("High School: ")
g=input("How're you buddy: ")
h=input("Currently,what are you doing? ")
print(a,b,c,d,e,f,g,h)